from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow():
    def setupUi(self, DoublePendulum):
        DoublePendulum.setObjectName("DoublePendulum")
        DoublePendulum.resize(900, 650)
        self.centralWidget = QtWidgets.QWidget(DoublePendulum)
        self.centralWidget.setObjectName("centralWidget")
        self.m1 = QtWidgets.QLabel(self.centralWidget)
        self.m1.setGeometry(QtCore.QRect(25, 58, 51, 16))
        self.m1.setObjectName("m1")
        self.m2 = QtWidgets.QLabel(self.centralWidget)
        self.m2.setGeometry(QtCore.QRect(25, 88, 51, 16))
        self.m2.setObjectName("m2")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(25, 118, 51, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(25, 148, 51, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(25, 220, 41, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(25, 250, 41, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(25, 280, 41, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(25, 310, 41, 16))
        self.label_6.setObjectName("label_6")
        self.m1_Slider = QtWidgets.QSlider(self.centralWidget)
        self.m1_Slider.setGeometry(QtCore.QRect(80, 58, 140, 22))
        self.m1_Slider.setMinimum(1)
        self.m1_Slider.setMaximum(1000)
        self.m1_Slider.setPageStep(100)
        self.m1_Slider.setSliderPosition(100)
        self.m1_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.m1_Slider.setObjectName("m1_Slider")
        self.theta1_Slider = QtWidgets.QSlider(self.centralWidget)
        self.theta1_Slider.setGeometry(QtCore.QRect(80, 220, 140, 22))
        self.theta1_Slider.setMaximum(3600)
        self.theta1_Slider.setProperty("value", 2700)
        self.theta1_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.theta1_Slider.setObjectName("theta1_Slider")
        self.l1_Slider = QtWidgets.QSlider(self.centralWidget)
        self.l1_Slider.setGeometry(QtCore.QRect(80, 118, 140, 22))
        self.l1_Slider.setMinimum(1)
        self.l1_Slider.setMaximum(200)
        self.l1_Slider.setPageStep(20)
        self.l1_Slider.setProperty("value", 100)
        self.l1_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.l1_Slider.setObjectName("l1_Slider")
        self.vel1_Slider = QtWidgets.QSlider(self.centralWidget)
        self.vel1_Slider.setGeometry(QtCore.QRect(80, 280, 140, 22))
        self.vel1_Slider.setMaximum(4000)
        self.vel1_Slider.setPageStep(10)
        self.vel1_Slider.setProperty("value", 2000)
        self.vel1_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.vel1_Slider.setObjectName("vel1_Slider")
        self.vel2_Slider = QtWidgets.QSlider(self.centralWidget)
        self.vel2_Slider.setGeometry(QtCore.QRect(80, 310, 140, 22))
        self.vel2_Slider.setMaximum(4000)
        self.vel2_Slider.setPageStep(10)
        self.vel2_Slider.setProperty("value", 2000)
        self.vel2_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.vel2_Slider.setObjectName("vel2_Slider")
        self.theta2_Slider = QtWidgets.QSlider(self.centralWidget)
        self.theta2_Slider.setGeometry(QtCore.QRect(80, 250, 140, 22))
        self.theta2_Slider.setMaximum(3600)
        self.theta2_Slider.setProperty("value", 2700)
        self.theta2_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.theta2_Slider.setObjectName("theta2_Slider")
        self.l2_Slider = QtWidgets.QSlider(self.centralWidget)
        self.l2_Slider.setGeometry(QtCore.QRect(80, 148, 140, 22))
        self.l2_Slider.setMinimum(1)
        self.l2_Slider.setMaximum(200)
        self.l2_Slider.setPageStep(20)
        self.l2_Slider.setProperty("value", 100)
        self.l2_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.l2_Slider.setObjectName("l2_Slider")
        self.m2_Slider = QtWidgets.QSlider(self.centralWidget)
        self.m2_Slider.setGeometry(QtCore.QRect(80, 88, 140, 22))
        self.m2_Slider.setMinimum(1)
        self.m2_Slider.setMaximum(1000)
        self.m2_Slider.setPageStep(100)
        self.m2_Slider.setProperty("value", 100)
        self.m2_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.m2_Slider.setObjectName("m2_Slider")
        self.m1_SpinBox = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.m1_SpinBox.setGeometry(QtCore.QRect(230, 56, 68, 22))
        self.m1_SpinBox.setMinimum(0.01)
        self.m1_SpinBox.setMaximum(10.0)
        self.m1_SpinBox.setSingleStep(0.01)
        self.m1_SpinBox.setProperty("value", 1.0)
        self.m1_SpinBox.setObjectName("m1_SpinBox")
        self.m2_SpinBox = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.m2_SpinBox.setGeometry(QtCore.QRect(230, 86, 68, 22))
        self.m2_SpinBox.setMinimum(0.01)
        self.m2_SpinBox.setMaximum(10.0)
        self.m2_SpinBox.setSingleStep(0.01)
        self.m2_SpinBox.setProperty("value", 1.0)
        self.m2_SpinBox.setObjectName("m2_SpinBox")
        self.l1_SpinBox = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.l1_SpinBox.setGeometry(QtCore.QRect(230, 118, 68, 22))
        self.l1_SpinBox.setMinimum(0.01)
        self.l1_SpinBox.setMaximum(2.0)
        self.l1_SpinBox.setSingleStep(0.01)
        self.l1_SpinBox.setProperty("value", 1.0)
        self.l1_SpinBox.setObjectName("l1_SpinBox")
        self.l2_SpinBox = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.l2_SpinBox.setGeometry(QtCore.QRect(230, 148, 68, 22))
        self.l2_SpinBox.setMinimum(0.01)
        self.l2_SpinBox.setMaximum(2.0)
        self.l2_SpinBox.setSingleStep(0.01)
        self.l2_SpinBox.setProperty("value", 1.0)
        self.l2_SpinBox.setObjectName("l2_SpinBox")
        self.theta1_SpinBox = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.theta1_SpinBox.setGeometry(QtCore.QRect(230, 218, 68, 22))
        self.theta1_SpinBox.setDecimals(1)
        self.theta1_SpinBox.setMinimum(-180.0)
        self.theta1_SpinBox.setMaximum(180.0)
        self.theta1_SpinBox.setSingleStep(0.1)
        self.theta1_SpinBox.setProperty("value", 90.0)
        self.theta1_SpinBox.setObjectName("theta1_SpinBox")
        self.theta2_SpinBox = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.theta2_SpinBox.setGeometry(QtCore.QRect(230, 248, 68, 22))
        self.theta2_SpinBox.setDecimals(1)
        self.theta2_SpinBox.setMinimum(-180.0)
        self.theta2_SpinBox.setMaximum(180.0)
        self.theta2_SpinBox.setSingleStep(0.1)
        self.theta2_SpinBox.setProperty("value", 90.0)
        self.theta2_SpinBox.setObjectName("theta2_SpinBox")
        self.vel1_SpinBox = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.vel1_SpinBox.setGeometry(QtCore.QRect(230, 278, 68, 22))
        self.vel1_SpinBox.setDecimals(1)
        self.vel1_SpinBox.setMinimum(-200.0)
        self.vel1_SpinBox.setMaximum(200.0)
        self.vel1_SpinBox.setSingleStep(0.1)
        self.vel1_SpinBox.setObjectName("vel1_SpinBox")
        self.vel2_SpinBox = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.vel2_SpinBox.setGeometry(QtCore.QRect(230, 308, 68, 22))
        self.vel2_SpinBox.setDecimals(1)
        self.vel2_SpinBox.setMinimum(-200.0)
        self.vel2_SpinBox.setMaximum(200.0)
        self.vel2_SpinBox.setSingleStep(0.1)
        self.vel2_SpinBox.setObjectName("vel2_SpinBox")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(25, 380, 31, 16))
        self.label_7.setObjectName("label_7")
        self.g_Slider = QtWidgets.QSlider(self.centralWidget)
        self.g_Slider.setGeometry(QtCore.QRect(80, 380, 140, 22))
        self.g_Slider.setMinimum(100)
        self.g_Slider.setMaximum(2000)
        self.g_Slider.setPageStep(100)
        self.g_Slider.setProperty("value", 980)
        self.g_Slider.setOrientation(QtCore.Qt.Horizontal)
        self.g_Slider.setObjectName("g_Slider")
        self.g_SpinBox = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.g_SpinBox.setGeometry(QtCore.QRect(230, 378, 68, 22))
        self.g_SpinBox.setMinimum(1.0)
        self.g_SpinBox.setMaximum(20.0)
        self.g_SpinBox.setSingleStep(0.01)
        self.g_SpinBox.setProperty("value", 9.8)
        self.g_SpinBox.setObjectName("g_SpinBox")
        self.StartButton = QtWidgets.QPushButton(self.centralWidget)
        self.StartButton.setGeometry(QtCore.QRect(40, 470, 113, 32))
        self.StartButton.setObjectName("StartButton")
        self.DefaultButton = QtWidgets.QPushButton(self.centralWidget)
        self.DefaultButton.setGeometry(QtCore.QRect(105, 410, 113, 32))
        self.DefaultButton.setObjectName("DefaultButton")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsView.setGeometry(QtCore.QRect(320, 10, 570, 570))
        self.graphicsView.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.TextAntialiasing)
        self.graphicsView.setObjectName("graphicsView")
        self.PauseButton = QtWidgets.QPushButton(self.centralWidget)
        self.PauseButton.setGeometry(QtCore.QRect(175, 470, 113, 32))
        self.PauseButton.setObjectName("PauseButton")
        self.StopButton = QtWidgets.QPushButton(self.centralWidget)
        self.StopButton.setGeometry(QtCore.QRect(175, 510, 113, 32))
        self.StopButton.setObjectName("StopButton")
        self.ResumeButton = QtWidgets.QPushButton(self.centralWidget)
        self.ResumeButton.setGeometry(QtCore.QRect(40, 510, 113, 32))
        self.ResumeButton.setObjectName("ResumeButton")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(11, 28, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(10, 40, 141, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_9 = QtWidgets.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(11, 190, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setGeometry(QtCore.QRect(10, 210, 113, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(11, 346, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.line_3 = QtWidgets.QFrame(self.centralWidget)
        self.line_3.setGeometry(QtCore.QRect(10, 366, 136, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralWidget)
        self.line_4.setGeometry(QtCore.QRect(10, 450, 300, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        DoublePendulum.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(DoublePendulum)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 900, 22))
        self.menuBar.setObjectName("menuBar")
        DoublePendulum.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(DoublePendulum)
        self.mainToolBar.setObjectName("mainToolBar")
        DoublePendulum.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(DoublePendulum)
        self.statusBar.setObjectName("statusBar")
        DoublePendulum.setStatusBar(self.statusBar)

        self.retranslateUi(DoublePendulum)
        QtCore.QMetaObject.connectSlotsByName(DoublePendulum)

    def retranslateUi(self, DoublePendulum):
        _translate = QtCore.QCoreApplication.translate
        DoublePendulum.setWindowTitle(_translate("DoublePendulum", "MainWindow"))
        self.m1.setText(_translate("DoublePendulum", "mass1"))
        self.m2.setText(_translate("DoublePendulum", "mass2"))
        self.label.setText(_translate("DoublePendulum", "length1"))
        self.label_2.setText(_translate("DoublePendulum", "length2"))
        self.label_3.setText(_translate("DoublePendulum", "theta1"))
        self.label_4.setText(_translate("DoublePendulum", "theta2"))
        self.label_5.setText(_translate("DoublePendulum", "vel1"))
        self.label_6.setText(_translate("DoublePendulum", "vel2"))
        self.label_7.setText(_translate("DoublePendulum", "g"))
        self.StartButton.setText(_translate("DoublePendulum", "Start"))
        self.DefaultButton.setText(_translate("DoublePendulum", "Default"))
        self.PauseButton.setText(_translate("DoublePendulum", "Pause"))
        self.StopButton.setText(_translate("DoublePendulum", "Stop"))
        self.ResumeButton.setText(_translate("DoublePendulum", "Resume"))
        self.label_8.setText(_translate("DoublePendulum", "Pendulum Properties"))
        self.label_9.setText(_translate("DoublePendulum", "Initial Conditions"))
        self.label_10.setText(_translate("DoublePendulum", "Gravity Acceleration"))
